### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by rixlabs** [springboot-angular2-tutorial/boot-app#4]
Hi,

this is not a real issue, more a request for infos.

Can you explain in few word how does the login procedure work?
Or better why didn't you use a "normal" controller for receiving the auth data?

A you can see I've got problem understanding the StatelessLoginFilter :)

good job anyway lot's of good examples! keep it up

**Comment by akirasosa** [comment]
@rixlabs 
It uses Spring Security. So, I have to use filter instead of controller to make user logged in.

I agree with your point. Actually, this app does not use the functionality of Spring Security so much. In this case, it would be better to use simple controller without Spring Security. I can see an example below.

https://github.com/nielsutrecht/jwt-angular-spring

This example does not use Spring Security. It looks simple enough.

**Comment by rixlabs** [comment]
@akirasosa thanks for the super fast answere!
Even with spring security you can use a controller for a stateless authentication.
I used [this ](https://github.com/brahalla/Cerberus/blob/master/src/main/java/com/brahalla/Cerberus/controller/rest/AuthenticationController.java) (from [Cerberus ](https://github.com/brahalla/Cerberus)project)as example in another project and it works well.
If you're interested I can branch and refactor that part so there is another example.

**Comment by akirasosa** [comment]
@rixlabs Thanks for information. I didn't know it...

> If you're interested I can branch and refactor that part so there is another example.

Yes. It will be a great improvement. Thanks!

**Comment by akirasosa** [comment]
Done on #5
